set(ECL_COMPLEX_FLOAT "0" CACHE STRING "Complex numbers enabled")

if(ECL_ENABLE_C99COMPLEX)

include(CheckFunctionExists)
include(CheckTypeSize)

# For C, ensure complex.h is checked first or included in CMAKE_EXTRA_INCLUDE_FILES
set(CMAKE_EXTRA_INCLUDE_FILES "complex.h")

# Linux/MacOS only
# TODO Windows
find_library(MATH_LIBRARY m)
if(MATH_LIBRARY)
    set(CMAKE_REQUIRED_LIBRARIES ${MATH_LIBRARY})
endif()

check_function_exists(crealf  HAVE_CREALF)
check_function_exists(creal   HAVE_CREAL)
check_function_exists(creall  HAVE_CREALL)
check_function_exists(cimagf  HAVE_CIMAGF)
check_function_exists(cimag   HAVE_CIMAG)
check_function_exists(cimagl  HAVE_CIMAGL)
check_function_exists(cabsf   HAVE_CABSF)
check_function_exists(cabs    HAVE_CABS)
check_function_exists(cabsl   HAVE_CABSL)
check_function_exists(conjf   HAVE_CONJF)
check_function_exists(conj    HAVE_CONJ)
check_function_exists(conjl   HAVE_CONJL)
check_function_exists(csqrtf  HAVE_CSQRTF)
check_function_exists(csqrt   HAVE_CSQRT)
check_function_exists(csqrtl  HAVE_CSQRTL)
check_function_exists(ccosf   HAVE_CCOSF)
check_function_exists(ccos    HAVE_CCOS)
check_function_exists(ccosl   HAVE_CCOSL)
check_function_exists(csinf   HAVE_CSINF)
check_function_exists(csin    HAVE_CSIN)
check_function_exists(csinl   HAVE_CSINL)
check_function_exists(ctanf   HAVE_CTANF)
check_function_exists(ctan    HAVE_CTAN)
check_function_exists(ctanl   HAVE_CTANL)
check_function_exists(ccoshf  HAVE_CCOSHF)
check_function_exists(ccosh   HAVE_CCOSH)
check_function_exists(ccoshl  HAVE_CCOSHL)
check_function_exists(csinhf  HAVE_CSINHF)
check_function_exists(csinh   HAVE_CSINH)
check_function_exists(csinhl  HAVE_CSINHL)
check_function_exists(ctanhf  HAVE_CTANHF)
check_function_exists(ctanh   HAVE_CTANH)
check_function_exists(ctanhl  HAVE_CTANHL)
check_function_exists(cexpf   HAVE_CEXPF)
check_function_exists(cexp    HAVE_CEXP)
check_function_exists(cexpl   HAVE_CEXPL)
check_function_exists(cpowf   HAVE_CPOWF)
check_function_exists(cpow    HAVE_CPOW)
check_function_exists(cpowl   HAVE_CPOWL)
check_function_exists(clogf   HAVE_CLOGF)
check_function_exists(clog    HAVE_CLOG)
check_function_exists(clogl   HAVE_CLOGL)
check_function_exists(casinf  HAVE_CASINF)
check_function_exists(casin   HAVE_CASIN)
check_function_exists(casinl  HAVE_CASINL)
check_function_exists(cacosf  HAVE_CACOSF)
check_function_exists(cacos   HAVE_CACOS)
check_function_exists(cacosl  HAVE_CACOSL)
check_function_exists(catanf  HAVE_CATANF)
check_function_exists(catan   HAVE_CATAN)
check_function_exists(catanl  HAVE_CATANL)
check_function_exists(casinhf HAVE_CASINHF)
check_function_exists(casinh  HAVE_CASINH)
check_function_exists(casinhl HAVE_CASINHL)
check_function_exists(cacoshf HAVE_CACOSHF)
check_function_exists(cacosh  HAVE_CACOSH)
check_function_exists(cacoshl HAVE_CACOSHL)
check_function_exists(catanhf HAVE_CATANHF)
check_function_exists(catanh  HAVE_CATANH)
check_function_exists(catanhl HAVE_CATANHL)

check_type_size("float complex"  SIZEOF_COMPLEX_FLOAT)
check_type_size("double complex" SIZEOF_COMPLEX_DOUBLE)
check_type_size("long complex"   SIZEOF_COMPLEX_LONG)

if(SIZEOF_COMPLEX_FLOAT)
    message(STATUS "Complex float size: ${SIZEOF_COMPLEX_FLOAT}")
endif()

if(SIZEOF_COMPLEX_DOUBLE)
    message(STATUS "Complex double size: ${SIZEOF_COMPLEX_DOUBLE}")
endif()

if(SIZEOF_COMPLEX_LONG)
    message(STATUS "Complex long size: ${SIZEOF_COMPLEX_LONG}")
endif()

if (SIZEOF_COMPLEX_FLOAT AND SIZEOF_COMPLEX_DOUBLE AND SIZEOF_COMPLEX_LONG)
  set(ECL_COMPLEX_FLOAT 1)
endif()

list(APPEND LSP_FEATURES :complex-float)

endif()