set(ECL_VERSION "24.5.10" CACHE STRING "ECL version")
set(ECL_VERSION_NUMBER "240510" CACHE STRING "ECL version as number")
set(ECL_USE_DBGHELP ${ECL_DEBUG})

set(configure_input "Generated by CMake")

#set(ECL_CFLAGS)         # Similar, but specific to ECL (see src/util/ecl-config)
#set(DEBUG_CFLAGS)

#set(GMP_CPPFLAGS)            # CFLAGS needed for compiling with system GMP library
#set(GMP_LDFLAGS)             # LDFLAGS needed for compiling with system GMP library
#set(LIBFFI_LDFLAGS)          # LDFLAGS needed for compiling with system LIBFFI library

#set(FASL_LIBS)               # Libraries to link into all ecl code but not
                             # into helper programs.
#set(CORE_LIBS)               # Locally compiled libs to link into
                             # ecl/ecl_min/libecl.so and nowhere else.
#set(SHARED_LDFLAGS)          # Flags for shared libraries linker
#set(BUNDLE_LDFLAGS)          # Flags for FASL files linker
#set(PROGRAM_LDFLAGS)         # Flags for executable program linker
#set(EXTRA_OBJS)              # Extra *.o files to be compiled into libecl.a
#set(TARGETS "bin/ecl${EXE}") # Versions of ECL to be built 
#set(SUBDIRS, "c" "doc")      # Subdirectories that make should process
#set(LIBRARIES)               # GMP, Boehm's GC, etc
set(LSP_LIBRARIES)           # Libraries produced by lisp translator
set(COMPILATION_FEATURES)    # Symbols to add to *FEATURES* for conditional compilation

set(LISP_PAGESIZE "2048" CACHE STRING "Page size in bytes")
set(MAXPAGE "65536" CACHE STRING "Maximum Memory Size")
set(ECL_MAX_STRING_POOL_SIZE "10" CACHE STRING "Number of strings in a pool")
set(ECL_BUFFER_STRING_SIZE "4192" CACHE STRING "Size of a string buffer to speedup reading")
set(ECL_SLOTS_LIMIT "32768" CACHE STRING "Structure/Instance limits. The index to a slot must fit in the \"int\" type.")
set(ECL_CALL_ARGUMENTS_LIMIT "65536" CACHE STRING "Maximum number of function arguments (arbitrary)")
set(ECL_LAMBDA_PARAMETERS_LIMIT ${ECL_CALL_ARGUMENTS_LIMIT} CACHE STRING "Maximum number of required arguments")

# See cmplam.lsp if you change value `ECL_C_ARGUMENTS_LIMIT`
set(ECL_C_ARGUMENTS_LIMIT "63" CACHE STRING "Numb. of args. which will be passed using the C stack")
set(ECL_MULTIPLE_VALUES_LIMIT "64" CACHE STRING "Maximum number of output arguments (>= ECL_C_ARGUMENTS_LIMIT)")
set(ECL_ARRAY_RANK_LIMIT "64" CACHE STRING "Array rank limit")
set(ECL_BIGNUM_REGISTER_NUMBER "3")
# Symbols to add to *FEATURES* in the final executable
set(LSP_FEATURES :ecl
                 :common
                 :common-lisp
                 :ansi-cl
#                :ffi
                 :prefixed-api
                 :cdr-14
                 :package-local-nicknames
                 :clos
                 :ecl-pde
                 :long-float)

if (CMAKE_SYSTEM_NAME STREQUAL "Windows")
    list(APPEND LSP_FEATURES :win32)
    list(APPEND LSP_FEATURES :windows)

    set(ECL_MS_WINDOWS_HOST 1)
    set(ECL_USE_GUARD_PAGE 1)

    if (ECL_USE_DBGHELP)
        set(ECL_WINDOWS_BACKTRACE 1)
    endif()

    if (ECL_ENABLE_THREADS)
        set(ECL_THREADS 1)
    else()
        message(FATAL_ERROR "Windows build does not work without threads support")
    endif()

    if(${CMAKE_HOST_SYSTEM_PROCESSOR} MATCHES "x86_64*|AMD64*")
        list(APPEND LSP_FEATURES :win64)
    endif()
endif()

if (CMAKE_SYSTEM_NAME STREQUAL "Darwin")
# TODO ARM64
    list(APPEND LSP_FEATURES :c-compatible-variadic-dispatch)
endif()

if (ECL_ENABLE_SERIALIZATION)
    list(APPEND LSP_FEATURES :externalizable)
endif()


### MSVC
if (MSVC)
    list(APPEND LSP_FEATURES :msvc)
endif()

### CMU format, CLOS streams
if (ECL_WITH_CMU_FORMAT)
    list(APPEND LSP_FEATURES :cmu-format)
    set(ECL_CMU_FORMAT 1)
    set(ECL_WITH_CLOS_STREAM ON)
endif()

if (ECL_WITH_CLOS_STREAM)
    set(ECL_CLOS_STREAMS 1)
    list(APPEND LSP_FEATURES :clos-streams)
endif()

if (ECL_ENABLE_SHARED)
    set(ENABLE_DLOPEN 1)
    list(APPEND COMPILATION_FEATURES :wants-dlopen)
endif()

if (ECL_ENABLE_THREADS)
    set(ECL_THREADS 1)
    list(APPEND LSP_FEATURES :ecl-read-write-lock)
    list(APPEND LSP_FEATURES :threads)
endif()

if (ECL_WITH_CMP)
    list(APPEND COMPILATION_FEATURES :wants-cmp)
endif()

#if (ECL_WITH_SERVE_EVENT)
#    list(APPEND COMPILATION_FEATURES :wants-serve_event)
#endif()

if (ECL_WITH_ASDF)
    if (ECL_ASDF_BUILTIN)
        list(APPEND COMPILATION_FEATURES :builtin-asdf)
    endif()

    list(APPEND COMPILATION_FEATURES :wants-asdf)
endif()

if (ECL_WITH_DEFSYSTEM)
    if (ECL_DEFSYSTEM_BUILTIN)
        list(APPEND COMPILATION_FEATURES :builtin-defsystem)
    endif()

    list(APPEND COMPILATION_FEATURES :wants-defsystem)
endif()

if (ECL_WITH_CMP)
    if (ECL_CMP_BUILTIN)
        list(APPEND COMPILATION_FEATURES :builtin-cmp)
    endif()

    list(APPEND COMPILATION_FEATURES :wants-cmp)
endif()

if (ECL_WITH_BYTECMP)
    if (ECL_BYTECMP_BUILTIN)
        list(APPEND COMPILATION_FEATURES :builtin-bytecmp)
    endif()

    list(APPEND COMPILATION_FEATURES :wants-bytecmp)
endif()

if (ECL_WITH_RT)
    if (ECL_RT_BUILTIN)
        list(APPEND COMPILATION_FEATURES :builtin-rt)
    endif()

    list(APPEND COMPILATION_FEATURES :wants-rt)
endif()

if (ECL_ENABLE_GMP)
  set(ECL_HAS_BIGNUM 1)
endif()