#cmakedefine ECL_COMPLEX_FLOAT @ECL_COMPLEX_FLOAT@

#cmakedefine HAVE_CREALF  @HAVE_CREALF@
#cmakedefine HAVE_CREAL   @HAVE_CREAL@
#cmakedefine HAVE_CREALL  @HAVE_CREALL@
#cmakedefine HAVE_CIMAGF  @HAVE_CIMAGF@
#cmakedefine HAVE_CIMAG   @HAVE_CIMAG@
#cmakedefine HAVE_CIMAGL  @HAVE_CIMAGL@
#cmakedefine HAVE_CABSF   @HAVE_CABSF@
#cmakedefine HAVE_CABS    @HAVE_CABS@
#cmakedefine HAVE_CABSL   @HAVE_CABSL@
#cmakedefine HAVE_CONJF   @HAVE_CONJF@
#cmakedefine HAVE_CONJ    @HAVE_CONJ@
#cmakedefine HAVE_CONJL   @HAVE_CONJL@
#cmakedefine HAVE_CSQRTF  @HAVE_CSQRTF@
#cmakedefine HAVE_CSQRT   @HAVE_CSQRT@
#cmakedefine HAVE_CSQRTL  @HAVE_CSQRTL@
#cmakedefine HAVE_CCOSF   @HAVE_CCOSF@
#cmakedefine HAVE_CCOS    @HAVE_CCOS@
#cmakedefine HAVE_CCOSL   @HAVE_CCOSL@
#cmakedefine HAVE_CSINF   @HAVE_CSINF@
#cmakedefine HAVE_CSIN    @HAVE_CSIN@
#cmakedefine HAVE_CSINL   @HAVE_CSINL@
#cmakedefine HAVE_CTANF   @HAVE_CTANF@
#cmakedefine HAVE_CTAN    @HAVE_CTAN@
#cmakedefine HAVE_CTANL   @HAVE_CTANL@
#cmakedefine HAVE_CCOSHF  @HAVE_CCOSHF@
#cmakedefine HAVE_CCOSH   @HAVE_CCOSH@
#cmakedefine HAVE_CCOSHL  @HAVE_CCOSHL@
#cmakedefine HAVE_CSINHF  @HAVE_CSINHF@
#cmakedefine HAVE_CSINH   @HAVE_CSINH@
#cmakedefine HAVE_CSINHL  @HAVE_CSINHL@
#cmakedefine HAVE_CTANHF  @HAVE_CTANHF@
#cmakedefine HAVE_CTANH   @HAVE_CTANH@
#cmakedefine HAVE_CTANHL  @HAVE_CTANHL@
#cmakedefine HAVE_CEXPF   @HAVE_CEXPF@
#cmakedefine HAVE_CEXP    @HAVE_CEXP@
#cmakedefine HAVE_CEXPL   @HAVE_CEXPL@
#cmakedefine HAVE_CPOWF   @HAVE_CPOWF@
#cmakedefine HAVE_CPOW    @HAVE_CPOW@
#cmakedefine HAVE_CPOWL   @HAVE_CPOWL@
#cmakedefine HAVE_CLOGF   @HAVE_CLOGF@
#cmakedefine HAVE_CLOG    @HAVE_CLOG@
#cmakedefine HAVE_CLOGL   @HAVE_CLOGL@
#cmakedefine HAVE_CASINF  @HAVE_CASINF@
#cmakedefine HAVE_CASIN   @HAVE_CASIN@
#cmakedefine HAVE_CASINL  @HAVE_CASINL@
#cmakedefine HAVE_CACOSF  @HAVE_CACOSF@
#cmakedefine HAVE_CACOS   @HAVE_CACOS@
#cmakedefine HAVE_CACOSL  @HAVE_CACOSL@
#cmakedefine HAVE_CATANF  @HAVE_CATANF@
#cmakedefine HAVE_CATAN   @HAVE_CATAN@
#cmakedefine HAVE_CATANL  @HAVE_CATANL@
#cmakedefine HAVE_CASINHF @HAVE_CASINHF@
#cmakedefine HAVE_CASINH  @HAVE_CASINH@
#cmakedefine HAVE_CASINHL @HAVE_CASINHL@
#cmakedefine HAVE_CACOSHF @HAVE_CACOSHF@
#cmakedefine HAVE_CACOSH  @HAVE_CACOSH@
#cmakedefine HAVE_CACOSHL @HAVE_CACOSHL@
#cmakedefine HAVE_CATANHF @HAVE_CATANHF@
#cmakedefine HAVE_CATANH  @HAVE_CATANH@
#cmakedefine HAVE_CATANHL @HAVE_CATANHL@
