#cmakedefine ECL_SETJMP                     @ECL_SETJMP@
#cmakedefine ECL_LONGJMP                    @ECL_LONGJMP@
#cmakedefine HAVE_NANOSLEEP                 @HAVE_NANOSLEEP@
#cmakedefine HAVE_ISNANF                    @HAVE_ISNANF@
#cmakedefine HAVE_SELECT                    @HAVE_SELECT@
#cmakedefine HAVE_SETENV                    @HAVE_SETENV@
#cmakedefine HAVE_PUTENV                    @HAVE_PUTENV@
#cmakedefine HAVE_TIMES                     @HAVE_TIMES@
#cmakedefine HAVE_GETTIMEOFDAY              @HAVE_GETTIMEOFDAY@
#cmakedefine HAVE_CLOCK_GETTIME             @HAVE_CLOCK_GETTIME@
#cmakedefine HAVE_GETRUSAGE                 @HAVE_GETRUSAGE@
#cmakedefine HAVE_LSTAT                     @HAVE_LSTAT@
#cmakedefine HAVE_MKSTEMP                   @HAVE_MKSTEMP@
#cmakedefine HAVE_ALARM                     @HAVE_ALARM@
#cmakedefine HAVE_SIGPROCMASK               @HAVE_SIGPROCMASK@
#cmakedefine HAVE_ISATTY                    @HAVE_ISATTY@
#cmakedefine HAVE_FSEEKO                    @HAVE_FSEEKO@
#cmakedefine HAVE_TZSET                     @HAVE_TZSET@
#cmakedefine HAVE_EXPF                      @HAVE_EXPF@
#cmakedefine HAVE_LOGF                      @HAVE_LOGF@
#cmakedefine HAVE_SQRTF                     @HAVE_SQRTF@
#cmakedefine HAVE_COSF                      @HAVE_COSF@
#cmakedefine HAVE_SINF                      @HAVE_SINF@
#cmakedefine HAVE_TANF                      @HAVE_TANF@
#cmakedefine HAVE_SINHF                     @HAVE_SINHF@
#cmakedefine HAVE_COSHF                     @HAVE_COSHF@
#cmakedefine HAVE_TANHF                     @HAVE_TANHF@
#cmakedefine HAVE_FLOORF                    @HAVE_FLOORF@
#cmakedefine HAVE_CEILF                     @HAVE_CEILF@
#cmakedefine HAVE_FABSF                     @HAVE_FABSF@
#cmakedefine HAVE_FREXPF                    @HAVE_FREXPF@
#cmakedefine HAVE_LDEXPF                    @HAVE_LDEXPF@
#cmakedefine HAVE_LOG1P                     @HAVE_LOG1P@
#cmakedefine HAVE_LOG1PF                    @HAVE_LOG1PF@
#cmakedefine HAVE_LOG1PL                    @HAVE_LOG1PL@
#cmakedefine HAVE_COPYSIGNF                 @HAVE_COPYSIGNF@
#cmakedefine HAVE_COPYSIGN                  @HAVE_COPYSIGN@
#cmakedefine HAVE_COPYSIGNL                 @HAVE_COPYSIGNL@
#cmakedefine HAVE_SCHED_YIELD               @HAVE_SCHED_YIELD@
#cmakedefine HAVE_SEM_INIT                  @HAVE_SEM_INIT@
#cmakedefine HAVE_PTHREAD_MUTEX_TIMEDLOCK   @HAVE_PTHREAD_MUTEX_TIMEDLOCK@
#cmakedefine HAVE_PTHREAD_CONDATTR_SETCLOCK @HAVE_PTHREAD_CONDATTR_SETCLOCK@
#cmakedefine HAVE_UNAME                     @HAVE_UNAME@
#cmakedefine HAVE_ENVIRON                   @HAVE_ENVIRON@
#cmakedefine HAVE_BACKTRACE                 @HAVE_BACKTRACE@
#cmakedefine HAVE_BACKTRACE_SYMBOLS         @HAVE_BACKTRACE_SYMBOLS@
#cmakedefine HAVE_SYSTEM                    @HAVE_SYSTEM@

#cmakedefine HAVE_PTHREAD_MUTEX_TIMEDLOCK   @HAVE_PTHREAD_MUTEX_TIMEDLOCK@
#cmakedefine HAVE_PTHREAD_CONDATTR_SETCLOCK @HAVE_PTHREAD_CONDATTR_SETCLOCK@

#cmakedefine ecl_setjmp                     @ecl_setjmp@
#cmakedefine ecl_longjmp                    @ecl_longjmp@
