include(CheckFunctionExists)
include(CheckSymbolExists)

# Jmp
set(ECL_SETJMP  "setjmp"  CACHE STRING "setjmp function")
set(ECL_LONGJMP "longjmp" CACHE STRING "longjmp function")

check_function_exists(_longjmp                  HAVE__LONGJMP)

if (HAVE__LONGJMP)
  set(ECL_SETJMP "_setjmp")
  set(ECL_LONGJMP "_longjmp")
endif()

check_function_exists(pthread_mutex_timedlock   HAVE_PTHREAD_MUTEX_TIMEDLOCK)
check_function_exists(pthread_condattr_setclock HAVE_PTHREAD_CONDATTR_SETCLOCK)

check_function_exists(nanosleep                 HAVE_NANOSLEEP)
check_function_exists(isnanf                    HAVE_ISNANF)
check_function_exists(select                    HAVE_SELECT)
check_function_exists(setenv                    HAVE_SETENV)
check_function_exists(putenv                    HAVE_PUTENV)
check_function_exists(times                     HAVE_TIMES)
check_function_exists(gettimeofday              HAVE_GETTIMEOFDAY)
check_function_exists(clock_gettime             HAVE_CLOCK_GETTIME)
check_function_exists(getrusage                 HAVE_GETRUSAGE)
check_function_exists(lstat                     HAVE_LSTAT)
check_function_exists(mkstemp                   HAVE_MKSTEMP)
check_function_exists(alarm                     HAVE_ALARM)
check_function_exists(sigprocmask               HAVE_SIGPROCMASK)
check_function_exists(isatty                    HAVE_ISATTY)
check_function_exists(fseeko                    HAVE_FSEEKO)
check_function_exists(tzset                     HAVE_TZSET)
check_function_exists(expf                      HAVE_EXPF)
check_function_exists(logf                      HAVE_LOGF)
check_function_exists(sqrtf                     HAVE_SQRTF)
check_function_exists(cosf                      HAVE_COSF)
check_function_exists(sinf                      HAVE_SINF)
check_function_exists(tanf                      HAVE_TANF)
check_function_exists(sinhf                     HAVE_SINHF)
check_function_exists(coshf                     HAVE_COSHF)
check_function_exists(tanhf                     HAVE_TANHF)
check_function_exists(floorf                    HAVE_FLOORF)
check_function_exists(ceilf                     HAVE_CEILF)
check_function_exists(fabsf                     HAVE_FABSF)
check_function_exists(frexpf                    HAVE_FREXPF)
check_function_exists(ldexpf                    HAVE_LDEXPF)
check_function_exists(log1p                     HAVE_LOG1P)
check_function_exists(log1pf                    HAVE_LOG1PF)
check_function_exists(log1pl                    HAVE_LOG1PL)
check_function_exists(copysignf                 HAVE_COPYSIGNF)
check_function_exists(copysign                  HAVE_COPYSIGN)
check_function_exists(copysignl                 HAVE_COPYSIGNL)
check_function_exists(sched_yield               HAVE_SCHED_YIELD)
check_function_exists(sem_init                  HAVE_SEM_INIT)
check_function_exists(pthread_mutex_timedlock   HAVE_PTHREAD_MUTEX_TIMEDLOCK)
check_function_exists(pthread_condattr_setclock HAVE_PTHREAD_CONDATTR_SETCLOCK)
check_function_exists(uname                     HAVE_UNAME)
check_function_exists(backtrace                 HAVE_BACKTRACE)
check_function_exists(backtrace_symbols         HAVE_BACKTRACE_SYMBOLS)
check_function_exists(system                    HAVE_SYSTEM)

## environ can be both symbol and macros
check_symbol_exists(environ "stdlib.h"          HAVE_ENVIRON)
if (NOT HAVE_ENVIRON)
  check_function_exists(environ                 HAVE_ENVIRON2)
  set(HAVE_ENVIRON ${HAVE_ENVIRON2})
endif()

set(ecl_setjmp  ${ECL_SETJMP})
set(ecl_longjmp  ${ECL_LONGJMP})
