include(CheckIncludeFiles)

check_include_files(sys/resource.h HAVE_SYS_RESOURCE_H)
check_include_files(sys/select.h   HAVE_SYS_SELECT_H)
check_include_files(sys/ioctl.h    HAVE_SYS_IOCTL_H)
check_include_files(sys/wait.h     HAVE_SYS_WAIT_H)
check_include_files(sys/mman.h     HAVE_SYS_MMAN_H)
check_include_files(ulimit.h       HAVE_ULIMIT_H)
check_include_files(float.h        HAVE_FLOAT_H)
check_include_files(dirent.h       HAVE_DIRENT_H)
check_include_files(dlfcn.h        HAVE_DLFCN_H)
check_include_files(link.h         HAVE_LINK_H)
check_include_files(mach-o/dyld.h  HAVE_MACH_O_DYLD_H)
check_include_files(unistd.h       HAVE_UNISTD_H)
check_include_files(sched.h        HAVE_SCHED_H)
check_include_files(fenv.h         HAVE_FENV_H)

if (HAVE_SYS_MMAN_H)
    set(ECL_USE_MPROTECT)
endif()
