option(ECL_ENABLE_SHARED      "Enable loading compiled files" ON)
option(ECL_ENABLE_RPATH       "Hard-code the location of the ECL shared library." OFF)
option(ECL_ENABLE_THREADS     "Support for native threads" ON)
option(ECL_ENABLE_LIBATOMIC   "Enable libatomic" ON)
option(ECL_ENABLE_SONAME      "Link and install the library using version numbers" ON)
option(ECL_ENABLE_GMP         "Use GMP library" OFF)
option(ECL_ENABLE_UNICODE     "Enable support for unicode" ON)
option(ECL_ENABLE_C99COMPLEX  "Include support for c99 complex floats" OFF)
option(ECL_ENABLE_SMALLCONS   "Include support for c99 complex floats" ON)
option(ECL_ENABLE_BOEHM       "Enable Boehm GC" ON)
option(ECL_ENABLE_GENGC       "Use generational garbage collection. Requires Boehm-Weiser GC" OFF)
option(ECL_ENABLE_PRECISEGC   "Use type information during garbage collection. Requires Boehm-Weiser GC (EXPERIMENTAL)" OFF)
option(ECL_ENABLE_SERIALIZATION "Use serialization framework instead of the reader to save externalizable objects in compiled files (EXPERIMENTAL)" OFF)
option(ECL_ENABLE_DEBUG       "Enable various debugging features" OFF)
option(ECL_CROSS_COMPILE      "Supply configuration for a cross compiler" OFF)

option(ECL_WITH_LIBFFI        "Enable libffi support"               OFF)
option(ECL_WITH_CXX           "Build ECL using C++ compiler"        OFF)
option(ECL_WITH_TCP           "Include socket interface"            OFF)
option(ECL_WITH_SERVE_EVENT   "Include serve-event module"           ON)
option(ECL_WITH_CLOS_STREAM   "User defined stream objects"          ON)
option(ECL_WITH_CMU_FORMAT    "Use CMUCL's FORMAT routine"           ON)
option(ECL_WITH_ASDF          "Include ASDF building facility"       ON)
option(ECL_WITH_DEFSYSTEM     "Include DEFSYSTEM building facility" OFF)
option(ECL_WITH_CMP           "Build the compiler"                   ON)
option(ECL_WITH_BYTECMP       "Build the bytecodes compiler"         ON)
option(ECL_WITH_DFFI          "Dynamic foreign function interface"  OFF)
option(ECL_WITH_FPE           "Detect floating point exceptions"     ON)
option(ECL_WITH_SIGNED_ZERO   "Allow for IEEE signed zeros"          ON)
option(ECL_WITH_IEEE_FP       "Full IEEE floating point system, including denormals" ON)
option(ECL_WITH_SSE           "Implement SSE intrinsics in ECL"      ON)
                             
option(ECL_DEBUG              "Build debug version of ECL"          OFF)

option(ECL_LIBATOMIC_INCLUDED "Use included version of the libatomic-ops library" ON)
option(ECL_BOEHM_INCLUDED     "Use included version of the Boehm GC library"      ON)

option(ECL_ASDF_BUILTIN       "Use included ASDF copy"           ON)
option(ECL_DEFSYSTEM_BUILTIN  "Use included defsystem facility"  ON)
option(ECL_CMP_BUILTIN        "Use included compiler copy"      OFF)
option(ECL_TCP_BUILTIN        "Use builtin TCP socket library"  OFF)
option(ECL_RT_BUILTIN         "Use builtin RT library"          OFF)
