if (ECL_WITH_TCP)
    set(ECL_TCP 1)
    if (WIN32) 
        list(APPEND LSP_FEATURES :wsock)
        set(ECL_WSOCK 1)
    endif()
    list(APPEND COMPILATION_FEATURES :wants-sockets)
    if (ECL_TCP_BUILTIN)
        list(APPEND COMPILATION_FEATURES :builtin-tcp)
    endif()
endif()
